### ISSUE TITLE
Exporting prescrition data

### ISSUE THREAD

**Issue by martin-datalogisk** [ADAPT/ISOv4Plugin#154]
In our application I am working on exporting prescription data from the apapt datamodel via ISOXML plug-in to an IOSXML file. Well my farms, fields, products data came out, but where is no prescrition, workitems and workoperatione data in the files.
Then I opened the visualizer project to try the same and debugged. I imported some working presciptiondata in the Visualizer they came in fine, just for the test I exported these data again from the visualizer, I expected to see some data, but there is no also no prescrition, workitems og workoperatione data exported, but there is fielddata, products and so on.
I think I must hav missed something.
I appricate some hints

**Comment by knelson-farmbeltnorth** [comment]
Hi Martin, did you perhaps omit setting the GridType export property?  I ran a test just now and that was the mistake I made.   If that is not the issue, is there any other information in the Plugin.Errors collection after the export?    If not, I'd recommend setting a breakpoint at TaskDataMapper.cs line 265 and stepping into the prescriptions block to see what may go wrong.

**Comment by martin-datalogisk** [comment]
Hi Kelly
Thanks, this was the hint I searched for
