### ISSUE TITLE
NuGet package name too generic

### ISSUE THREAD

**Issue by stevehipwell** [ADAPT/ISOv4Plugin#64]
The NuGet package name for this plugin is currently *AgGatewayISOPlugin* which is too generic and stops us building an ecosystem that supports handling multiple ISO XML versions.

My suggestion is that we start packaging this plugin as *AgGatewayISOv4Plugin* by default. We should still package this as *AgGatewayISOPlugin* but mark it in NuGet as deprecated.

Once v5 of ISO XML is released we would create new repository as a fork of this one and release the plugin as *AgGatewayISOv5Plugin*. Both the v4 and v5 plugins could then be used together. We could also create forks to handle v2 and v3 as not all devices have been updated to support v4.

**Comment by strhea** [comment]
@stevehipwell and @knelson-farmbeltnorth will coordinate to get this done in the next ISO plugin release.

**Comment by stevehipwell** [comment]
@knelson-farmbeltnorth I'll make a pull request and assign it to you. Shouldn't take long.

**Comment by stevehipwell** [comment]
@knelson-farmbeltnorth I've create merge request https://github.com/ADAPT/ISOv4Plugin/pull/65 to handle this.
